language: python
sudo: true
python:
  - "2.7"
  - "3.3"
  - "3.5"
env:
  - TEST_MODE=tests
install: .travis/install.sh
script: .travis/test.sh
matrix:
  include:
    - python: "2.7"
      env: TEST_MODE=coverage
    - python: "2.7"
      env: TEST_MODE=flake8
